---
dependencies:
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.bbg_ubuntu.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.bbg_ubuntu.key_url }}'
    when: ansible_architecture != "ppc64le"
