---
- name: update apt index
  apt: update_cache=yes cache_valid_time=3600

- name: update SSL
  apt: pkg={{ item }} state=latest
  with_items:
  - libssl1.0.0
  - openssl
  notify: reload haproxy

- name: update python modules for true ssl context
  pip: name={{ item }} state=latest
  with_items:
    - pyopenssl 
    - pyasn1 
    - ndg-httpsclient

- include: CVE-2015-0235.yml
  tags: CVE-2015-0235
  when: ansible_architecture != "ppc64le"
