---
- include: ssh.yml
  when: nova.enable_ssh|bool

- include: libvirt.yml
  when: nova.compute_driver == "nova.virt.libvirt.LibvirtDriver"

- include: docker.yml
  when: nova.compute_driver == "novadocker.virt.docker.DockerDriver"

- name: install nova data plan requirements
  apt: pkg=sysfsutils

- name: nova instances directory
  file:
    dest: "{{ nova.state_path }}/instances"
    state: directory
    owner: nova

- name: nbd module
  lineinfile: dest=/etc/modules line="nbd"

- name: probe nbd
  modprobe: name=nbd state=present

- lineinfile: dest=/etc/modules line="nbd"

- modprobe: name=nbd state=present

- name: enable cinder encryption
  template: src=etc/nova/nova.cinder_encryption.conf dest=/etc/nova/nova.cinder_encryption.conf mode=0640
            owner=root group=nova
  notify: restart nova services
  when: cinder.fixed_key is defined

- name: disable  cinder encryption
  file: dest=/etc/nova/nova.cinder_encryption.conf state=absent
  notify: restart nova services
  when: cinder.fixed_key is not defined

- name: install nova-compute service
  upstart_service: name=nova-compute user=nova cmd=/usr/local/bin/nova-compute
                   config_dirs=/etc/nova

- name: install nova-compute service for ubuntu 15.04, Copy nova-compute.service
  copy: src=lib/systemd/system/nova-compute.service dest=/lib/systemd/system/nova-compute.service mode=0644
  when: ansible_distribution_version == "15.04"

- name: install nova-compute service for ubuntu 15.04, Reload systemctl
  command: systemctl daemon-reload
  when: ansible_distribution_version == "15.04"

- name: start nova-compute
  service: name=nova-compute state=started

- include: monitoring.yml tags=monitoring,common
  when: monitoring.enabled|default('True')|bool
  when: ansible_distribution_version != "15.04" and ansible_architecture != "ppc64le"
