---
dependencies:
  - role: apt-repos
    repos:
      - name: 'collectd package repo'
        repo: 'deb {{ collectd.apt_repo }} {{ ansible_distribution_release }} main'
        key_url: '{{ collectd.key_url }}'
    when: ansible_distribution_version == "12.04" and ansible_architecture != "ppc64le"
