---
- name: install log template
  template: src=etc/logstash-forwarder.d/template.conf dest=/etc/logstash-forwarder.d/{{ service }}.conf
  notify: restart logstash-forwarder
  when: ansible_architecture != "ppc64le"
